version: '3'

services:
  db:
    container_name: django_react_db
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}

  backend:
    container_name: django_react_backend
    build:
      context: ./backend
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: |
      bash -c "if [ ! -f manage.py ]; then
        django-admin startproject ${DJANGO_PROJECT_NAME} .;
      fi;
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - ${DJANGO_PORT}
    depends_on:
      - db

  frontend:
    container_name: django_react_frontend
    build:
      context: ./frontend
      args:
        NODE_VERSION: ${NODE_VERSION}
    command: |
      bash -c "if [ ! -d ${REACT_PROJECT_NAME} ]; then
        npx create-react-app ${REACT_PROJECT_NAME};
      fi;
      cd ${REACT_PROJECT_NAME} && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - ${REACT_PORT}
    depends_on:
      - backend
